services:
  - type: web
    name: sama-net-alert
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn flask_server:app
    envVars:
      - key: FLASK_APP
        value: telegram_listener.py
      - key: FLASK_ENV
        value: production
    autoDeploy: true
